Feature/donut chart
Orfium/orfium-ictinus pull request #167
Opened 2021-01-21 10:47 UTC by SVonKarajann

## Description

Implement a DonutChart component for the DS

PR depends on #160 

## Screenshot

<img width="120" alt="donut-chart" src="https://user-images.githubusercontent.com/24905735/105339959-f1f5fa80-5be5-11eb-8b52-87ce9084cd7e.png">

## Test Plan

2021-02-12 08:35 UTC, SVonKarajann commented
![reminder](https://user-images.githubusercontent.com/24905735/107746096-f8c3e900-6d1d-11eb-8760-078933104298.jpg)

2021-02-12 13:59 UTC, Christos-Zacharopoulos requested changes

2021-02-12 13:59 UTC, Christos-Zacharopoulos commented on src/components/Chart/BarChart/components/CustomLabel/CustomLabel.tsx
> +interface CustomLabelProps extends LabelProps {
Again, change to type as it's mostly preferred in the project.

2021-02-12 13:59 UTC, Christos-Zacharopoulos commented
I don't see any Tooltip in the designs but are we sure that we don't need one?  Maybe it's something to consider as a change for the future.

2021-02-15 14:48 UTC, SVonKarajann commented
> I don't see any Tooltip in the designs but are we sure that we don't need one? Maybe it's something to consider as a change for the future.

indeed, we could add a tooltip in the future if needed

2021-02-15 15:04 UTC, Christos-Zacharopoulos approved these changes

2021-02-15 15:05 UTC, merged