[DS-192, DS-193] Feat/table styling fixes
Orfium/orfium-ictinus pull request #307
Opened 2021-06-18 10:10 UTC by Christos-Zacharopoulos

## Description

This PR resolves a few more styling issues found. Divider between rows color change and nested header styling fixes.

Tickets: [DS-192](https://orfium.atlassian.net/browse/DS-192), [DS-193](https://orfium.atlassian.net/browse/DS-193)

## Screenshot

![image](https://user-images.githubusercontent.com/28539607/122545341-68344700-d036-11eb-95d4-fe53e1e84d82.png)

## Tests

Updated snapshots

2021-06-22 07:28 UTC, panvourtsis requested changes

2021-06-22 07:28 UTC, panvourtsis commented on src/components/Table/components/RenderRowOrNestedRow/RenderRowOrNestedRow.tsx
> +        css={borderedRowStyle(bordered)}
change function property to object for future use

2021-06-22 07:28 UTC, panvourtsis commented on src/components/Table/components/RenderRowOrNestedRow/RenderRowOrNestedRow.tsx
> +            <div css={expandableRowStyle(rowIndex === 1)}>
hange function property to object for future use

2021-06-22 07:28 UTC, panvourtsis commented on src/components/Table/components/RenderRowOrNestedRow/components/ContentCell/ContentCell.tsx
> +    textAlign={align ? align : columnsHasNumberArr[cellCounter] ? 'right' : 'left'}
as you touched this part can we give `columnsHasNumberArr[cellCounter]` this a const name and use this. It will be readable

2021-06-22 07:32 UTC, SVonKarajann approved these changes
LGTM

2021-06-23 06:27 UTC, panvourtsis approved these changes

2021-06-23 07:37 UTC, merged