feat: changes step in color util
Orfium/orfium-ictinus pull request #331
Opened 2021-07-19 09:13 UTC by michalisKout

## Description 

- changes step in color util from 10% to 5% after design team request.

2021-07-19 09:43 UTC, elektracodes approved these changes

2021-07-19 10:33 UTC, panvourtsis commented
shall i recommend put in a ticket for this?

2021-07-19 10:34 UTC, panvourtsis commented on src/components/storyUtils/ColorUtility/useColors.ts
> +  console.log(step);
remove console log

2021-07-20 07:54 UTC, michalisKout commented
> shall i recommend put in a ticket for this?

This would help a lot. Although even if we create a ticket, the design team has to define the acceptance criteria for this tool.

2021-07-29 09:23 UTC, michalisKout commented
@panvourtsis based on the last conversation we had in DS refinement, can we merge this to master?

2021-07-29 09:26 UTC, panvourtsis commented
> @panvourtsis based on the last conversation we had in DS refinement, can we merge this to master (without opening a task)?

that the reason. We want the criteria in order to see what is changing, breaking etc

2021-07-30 11:25 UTC, panvourtsis requested changes
On our latest talk with design team we said that we will need to do a research around the tool they are using to avoid the inconsistencies from our tool. Check ticket for more

2021-07-30 11:44 UTC, michalisKout commented
> On our latest talk with design team we said that we will need to do a research around the tool they are using to avoid the inconsistencies from our tool. Check ticket for more

I checked your comment in Jira and I agree that we should investigate it more. 
Although I believe that this PR should be merged to master since this color utility already exists in the production version of Ictinus. 
This is just a fix to help designers work on their new color palette.

2021-08-04 09:44 UTC, panvourtsis commented
I am closing this as the ticket will change to a research around the tool that the design team is using

2021-08-04 09:44 UTC, closed without merging