[DS-288]: feat(breadcrumb): max length changed to 3, remove options from data
Orfium/orfium-ictinus pull request #432
Opened 2021-12-16 12:19 UTC by SVonKarajann

## Description

[Ticket](https://orfium.atlassian.net/browse/DS-288)

## Screenshot

## Test Plan

2021-12-16 16:12 UTC, whosyourtaco requested changes

2021-12-16 16:13 UTC, whosyourtaco approved these changes
(Requested changes by mistake). Nice job! 💯

2022-01-03 14:09 UTC, Christos-Zacharopoulos commented on src/components/Breadcrumb/BreadcrumbItem/BreadcrumbItem.tsx
> +  const { childComponent, isLastItem = false } = props;
You can do the props de-structure in the line above.

2022-01-03 14:13 UTC, Christos-Zacharopoulos commented on src/components/Breadcrumb/Breadcrumb.tsx
> +  const passDataToRouterLink = (dataItem: BreadcrumbItemData, index: number) => {
`passDataToRouterLink` ( as well as `isLastItem` ) don't need to access to scope variables and can be moved outside the component ( or even to a utils file )

2022-01-04 08:45 UTC, Christos-Zacharopoulos approved these changes

2022-01-04 09:03 UTC, merged