[NDS-705] NumberField [v5]
Orfium/orfium-ictinus pull request #649
Opened 2023-07-20 13:08 UTC by kostasdano

## Description

[NDS-705](https://orfium.atlassian.net/browse/NDS-705)

2023-07-24 11:52 UTC, panvourtsis commented
can we make another PR where all forms are as Figma?

Fields
- Number Field
- Text Field 
etc

2023-07-24 12:01 UTC, panvourtsis requested changes

2023-07-25 13:56 UTC, kostasdano commented on src/components/NumberField/NumberField.tsx
> +export type NumberFieldProps = Omit<TextFieldProps, 'mask' | 'maskChar' | 'value' | 'onChange'> & {
`suffix` and `isReadOnly` are needed, the other ones yes they should be omitted.

2023-07-27 11:57 UTC, panvourtsis approved these changes
good job well done 🍰 !

2023-07-27 11:58 UTC, merged