feat: adding event clickawaylistener
Orfium/orfium-ictinus pull request #713
Opened 2023-11-21 14:55 UTC by panvourtsis

## Description

This PR adds the event on clickAwayListner click

## Screenshot

## Test Plan

2023-11-30 09:30 UTC, mkarajohn requested changes

2023-11-30 09:31 UTC, mkarajohn requested changes

2023-11-30 09:31 UTC, mkarajohn commented on src/components/utils/ClickAwayListener/ClickAwayListener.tsx
> +  ref: React.MutableRefObject<HTMLElement | null>,
Import `type MutableRefObject` directly from `'react'`

2023-12-04 07:16 UTC, panvourtsis commented on src/components/utils/ClickAwayListener/ClickAwayListener.tsx
> +  useCapture = false
i do use the official one, there are two and we use a specific `eslint` rule that makes easier to use the second official one
![image](https://github.com/Orfium/orfium-ictinus/assets/6433679/f017e6d3-76df-4e52-b856-7360e98f4ca7)

2023-12-04 07:25 UTC, panvourtsis commented on src/components/utils/ClickAwayListener/ClickAwayListener.tsx
> +  ref: React.MutableRefObject<HTMLElement | null>,
fixed on https://github.com/Orfium/orfium-ictinus/pull/713/commits/5856215cdecd34ea090612a6d94a5467716bff0f

2023-12-04 07:25 UTC, panvourtsis commented on src/components/utils/ClickAwayListener/ClickAwayListener.tsx
> +  useCapture = false
default value changed on https://github.com/Orfium/orfium-ictinus/pull/713/commits/5856215cdecd34ea090612a6d94a5467716bff0f

2023-12-04 13:41 UTC, mkarajohn approved these changes

2023-12-05 13:40 UTC, merged